### ISSUE TITLE
COCO pretrained model

### ISSUE THREAD

**Issue by dennix94** [sukjunhwang/IFC#1]
Thanks for the code. 
It would be great if you could also share the COCO pretrained model.

**Comment by liangzhiyuanCV** [comment]
Thanks for your excellent work.
I also notice that the coco pre-trained model has not been available now. I would like to know when the pre-trained model could be released.

**Comment by sukjunhwang** [comment]
Hi @liangzhiyuanCV,

Sorry for the delay; I was OoO due to personal issues, and forgot about uploading it.
Here is the [link](https://drive.google.com/file/d/1qTG7IhHxSMFxWeLXnq5KJV7ve8sbmBm8/view?usp=sharing) for ResNet-50, and we suggest you to discard the weights of the class head (**detr.class_embed**) when fine-tuning to YouTube-VIS, as it easily overfits to the training set.
I will further elaborate and work on making it concise when I get back to office and have some time.

Thank you :)
