### ISSUE TITLE
Question about batch size vs num frames

### ISSUE THREAD

**Issue by cyrilzakka** [sukjunhwang/IFC#7]
Hello again,

I have one last question that I'm still unclear about. In this implementation, the size of the input being fed into the network is (B x C x H x W) with B being the number of frames correct? Or is it actually (B x F x C x H x W) with F being the number of frames?

**Comment by sukjunhwang** [comment]
Hi @cyrilzakka 

The initial input shape is of BF x C x H x W, batch_size and num_frames flattened together.
Before the transformer encoder phase, all the computations are independent among each frame.
The idea behind flattening batch_size and num_frame is that pytorch's conv2d operations take input of (batch, channel, height, width).
In order to make computations separate and avoid the use of 'for loops', we flatten batch_size and num_frames.

**Comment by cyrilzakka** [comment]
Thanks for the answer! Would you mind pointing me at the line of code responsible for converting B x F x C X H X W to BF x C X H X W and then back prior to the transformer?

**Comment by sukjunhwang** [comment]
https://github.com/sukjunhwang/IFC/blob/cfa38e3f31bbcf48b3426c413deeb558d37edceb/projects/IFC/ifc/ifc.py#L396-L405

Given the code above, all frames in all batched videos go into "images" list.
So, it is already the same to flattening B and F.

https://github.com/sukjunhwang/IFC/blob/cfa38e3f31bbcf48b3426c413deeb558d37edceb/projects/IFC/ifc/ifc.py#L192
Therefore, the shape of "video" tensor would be BF x 3 x H x W -- 3 denoting BGR

**Comment by cyrilzakka** [comment]
Thank you for your time!
